liip_imagine:
    filter_sets:
        # the name of the "filter set"
        thumb:
            # adjust the image quality to 75%
            quality : 75
            # list of transformations to apply (the "filters")
            filters :
               thumbnail:
                  size:         [320, 380]
                  mode:           outbound

        card:
          # adjust the image quality to 75%
          quality: 75
          # list of transformations to apply (the "filters")
          filters:
            thumbnail:
              size:         [80,80]
              mode:           outbound

        detail:
          # adjust the image quality to 75%
          quality: 75
          # list of transformations to apply (the "filters")
          filters:
            thumbnail:
              size:         [650,665]
              mode:           outbound

        produit_boutique:
                # adjust the image quality to 75%
                quality: 75
                # list of transformations to apply (the "filters")
                filters:
                  thumbnail:
                    size:         [302,365]
                    mode:           outbound
        boutique_icon:
          # adjust the image quality to 75%
          quality: 75
          # list of transformations to apply (the "filters")
          filters:
            thumbnail:
              size:         [970,580]
              mode:           outbound